name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NPM install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Lint
        run: npm run lint:ci

      - name: Test
        run: npm run test:ci

      - name: Upload failed comparison results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: 'screenshot-diff'
          path: __tests__/__image_snapshots__/__diff_output__

      - name: Semantic release
        if: github.ref == 'refs/heads/master'
        run: npx --no-install semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate docs
        if: github.ref == 'refs/heads/master'
        run: npm run docs

      - name: Deploy to GH pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
